name: "hicexplorer_hicplotmatrix"
description: Creates a heatmap of a Hi-C matrix
keywords:
  - plots
tools:
  - "hicexplorer":
      description: "Set of programs to process, analyze and visualize Hi-C and capture Hi-C data"
      homepage: "https://hicexplorer.readthedocs.io"
      documentation: "https://hicexplorer.readthedocs.io"
      tool_dev_url: "https://github.com/deeptools/HiCExplorer"
      doi: "10.1038/s41467-017-02525-w"
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', bin:50000 ]
  - matrix:
      type: file
      description: HiCExplorer matrix in h5 format
  - additional_files:
      type: file
      description: additional files used for plots

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', bin:50000 ]
  #
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  #
  - plots:
      type: file
      description: Plots generated by hicPlotMatrix

authors:
  - "@jianhong"
