name: motus_profile
description: Taxonomic meta-omics profiling using universal marker genes
keywords:
  - classify
  - metagenomics
  - fastq
  - taxonomic profiling
tools:
  - motus:
      description: The mOTU profiler is a computational tool that estimates relative taxonomic abundance of known and currently unknown microbial community members using metagenomic shotgun sequencing data.
      homepage: https://github.com/motu-tool/mOTUs
      documentation: https://github.com/motu-tool/mOTUs/wiki
      tool_dev_url: https://github.com/motu-tool/mOTUs
      doi: "10.1038/s41467-019-08844-4"
      licence: ["GNU GPL v3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input fastq/fasta files of size 1 and 2 for single-end and paired-end data,
        respectively.
      pattern: "*.{fastq,fq,fasta,fa,fsa,fas,fna,fastq.gz,fq.gz,fasta.gz,fa.gz,fsa.gz,fas.gz,fna.gz}"
  - db:
      type: files
      description: |
        mOTUs database downloaded by `motus downloadDB`

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - motus_out:
      type: file
      description: Results with taxonomic classification of each read
      pattern: "*.motus.out"
  - krona_input:
      type: file
      description: Input file for Krona plots
      pattern: "*.motus.out.krona"

authors:
  - "@jianhong"
