name: lofreq_call
description: Lofreq subcommand to call low frequency variants from alignments
keywords:
  - variant calling
  - low frequency variant calling
  - lofreq
  - lofreq/call
tools:
  - lofreq:
      description: A fast and sensitive variant-caller for inferring SNVs and indels from next-generation sequencing data
      homepage: https://csb5.github.io/lofreq/
      documentation: https://csb5.github.io/lofreq/commands/
      doi: "10.1093/nar/gks918 "
      licence: ['MIT']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - ipbam:
      type: file
      description: Treatment file
  - controlbam:
      type: file
      description: The control file

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - peak:
      type: file
      description: narrowPeak or broadPeak output file
      pattern: "*.{narrowPeak,broadPeak}"
  - xls:
      type: file
      description: xls output file
      pattern: "*.{xls}"
  - gapped:
      type: file
      description: gappedPeak output file
      pattern: "*.{gappedPeak}"
  - bed:
      type: file
      description: bed output file
      pattern: "*.{bed}"
  - bdg:
      type: file
      description: bedgraph output file
      pattern: "*.{bdg}"

authors:
  - "@nf-core-team, updated by @jianhong"
